package masera.deviajesearches.dtos.amadeus.response;

import java.util.HashMap;
import java.util.Map;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO que representa una ciudad.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CityDto {

  private String name;
  private String iataCode;
  private String country;

  /**
   * Obtiene el nombre completo del país a partir de su código ISO.
   */
  public String getCountryName(String countryCode) {
    Map<String, String> countryMap = new HashMap<>();
    countryMap.put("AF", "Afganistán");
    countryMap.put("AL", "Albania");
    countryMap.put("DE", "Alemania");
    countryMap.put("AD", "Andorra");
    countryMap.put("AO", "Angola");
    countryMap.put("AI", "Anguila");
    countryMap.put("AQ", "Antártida");
    countryMap.put("AG", "Antigua y Barbuda");
    countryMap.put("SA", "Arabia Saudita");
    countryMap.put("DZ", "Argelia");
    countryMap.put("AR", "Argentina");
    countryMap.put("AM", "Armenia");
    countryMap.put("AW", "Aruba");
    countryMap.put("AU", "Australia");
    countryMap.put("AT", "Austria");
    countryMap.put("AZ", "Azerbaiyán");
    countryMap.put("BS", "Bahamas");
    countryMap.put("BD", "Bangladés");
    countryMap.put("BB", "Barbados");
    countryMap.put("BH", "Baréin");
    countryMap.put("BE", "Bélgica");
    countryMap.put("BZ", "Belice");
    countryMap.put("BJ", "Benín");
    countryMap.put("BM", "Bermudas");
    countryMap.put("BY", "Bielorrusia");
    countryMap.put("BO", "Bolivia");
    countryMap.put("BA", "Bosnia y Herzegovina");
    countryMap.put("BW", "Botsuana");
    countryMap.put("BR", "Brasil");
    countryMap.put("BN", "Brunéi");
    countryMap.put("BG", "Bulgaria");
    countryMap.put("BF", "Burkina Faso");
    countryMap.put("BI", "Burundi");
    countryMap.put("BT", "Bután");
    countryMap.put("CV", "Cabo Verde");
    countryMap.put("KH", "Camboya");
    countryMap.put("CM", "Camerún");
    countryMap.put("CA", "Canadá");
    countryMap.put("QA", "Catar");
    countryMap.put("TD", "Chad");
    countryMap.put("CL", "Chile");
    countryMap.put("CN", "China");
    countryMap.put("CY", "Chipre");
    countryMap.put("VA", "Ciudad del Vaticano");
    countryMap.put("CO", "Colombia");
    countryMap.put("KM", "Comoras");
    countryMap.put("CG", "Congo");
    countryMap.put("CD", "Congo (Rep. Dem.)");
    countryMap.put("KP", "Corea del Norte");
    countryMap.put("KR", "Corea del Sur");
    countryMap.put("CI", "Costa de Marfil");
    countryMap.put("CR", "Costa Rica");
    countryMap.put("HR", "Croacia");
    countryMap.put("CU", "Cuba");
    countryMap.put("CW", "Curazao");
    countryMap.put("DK", "Dinamarca");
    countryMap.put("DM", "Dominica");
    countryMap.put("EC", "Ecuador");
    countryMap.put("EG", "Egipto");
    countryMap.put("SV", "El Salvador");
    countryMap.put("AE", "Emiratos Árabes Unidos");
    countryMap.put("ER", "Eritrea");
    countryMap.put("SK", "Eslovaquia");
    countryMap.put("SI", "Eslovenia");
    countryMap.put("ES", "España");
    countryMap.put("US", "Estados Unidos");
    countryMap.put("EE", "Estonia");
    countryMap.put("ET", "Etiopía");
    countryMap.put("PH", "Filipinas");
    countryMap.put("FI", "Finlandia");
    countryMap.put("FJ", "Fiyi");
    countryMap.put("FR", "Francia");
    countryMap.put("GA", "Gabón");
    countryMap.put("GM", "Gambia");
    countryMap.put("GE", "Georgia");
    countryMap.put("GH", "Ghana");
    countryMap.put("GI", "Gibraltar");
    countryMap.put("GD", "Granada");
    countryMap.put("GR", "Grecia");
    countryMap.put("GL", "Groenlandia");
    countryMap.put("GP", "Guadalupe");
    countryMap.put("GU", "Guam");
    countryMap.put("GT", "Guatemala");
    countryMap.put("GF", "Guayana Francesa");
    countryMap.put("GG", "Guernsey");
    countryMap.put("GN", "Guinea");
    countryMap.put("GQ", "Guinea Ecuatorial");
    countryMap.put("GW", "Guinea-Bisáu");
    countryMap.put("GY", "Guyana");
    countryMap.put("HT", "Haití");
    countryMap.put("HN", "Honduras");
    countryMap.put("HK", "Hong Kong");
    countryMap.put("HU", "Hungría");
    countryMap.put("IN", "India");
    countryMap.put("ID", "Indonesia");
    countryMap.put("IQ", "Irak");
    countryMap.put("IR", "Irán");
    countryMap.put("IE", "Irlanda");
    countryMap.put("IS", "Islandia");
    countryMap.put("IL", "Israel");
    countryMap.put("IT", "Italia");
    countryMap.put("JM", "Jamaica");
    countryMap.put("JP", "Japón");
    countryMap.put("JE", "Jersey");
    countryMap.put("JO", "Jordania");
    countryMap.put("KZ", "Kazajistán");
    countryMap.put("KE", "Kenia");
    countryMap.put("KG", "Kirguistán");
    countryMap.put("KI", "Kiribati");
    countryMap.put("KW", "Kuwait");
    countryMap.put("LA", "Laos");
    countryMap.put("LS", "Lesoto");
    countryMap.put("LV", "Letonia");
    countryMap.put("LB", "Líbano");
    countryMap.put("LR", "Liberia");
    countryMap.put("LY", "Libia");
    countryMap.put("LI", "Liechtenstein");
    countryMap.put("LT", "Lituania");
    countryMap.put("LU", "Luxemburgo");
    countryMap.put("MO", "Macao");
    countryMap.put("MK", "Macedonia del Norte");
    countryMap.put("MG", "Madagascar");
    countryMap.put("MY", "Malasia");
    countryMap.put("MW", "Malaui");
    countryMap.put("MV", "Maldivas");
    countryMap.put("ML", "Malí");
    countryMap.put("MT", "Malta");
    countryMap.put("MA", "Marruecos");
    countryMap.put("MQ", "Martinica");
    countryMap.put("MU", "Mauricio");
    countryMap.put("MR", "Mauritania");
    countryMap.put("YT", "Mayotte");
    countryMap.put("MX", "México");
    countryMap.put("FM", "Micronesia");
    countryMap.put("MD", "Moldavia");
    countryMap.put("MC", "Mónaco");
    countryMap.put("MN", "Mongolia");
    countryMap.put("ME", "Montenegro");
    countryMap.put("MS", "Montserrat");
    countryMap.put("MZ", "Mozambique");
    countryMap.put("MM", "Myanmar");
    countryMap.put("NA", "Namibia");
    countryMap.put("NR", "Nauru");
    countryMap.put("NP", "Nepal");
    countryMap.put("NI", "Nicaragua");
    countryMap.put("NE", "Níger");
    countryMap.put("NG", "Nigeria");
    countryMap.put("NU", "Niue");
    countryMap.put("NO", "Noruega");
    countryMap.put("NC", "Nueva Caledonia");
    countryMap.put("NZ", "Nueva Zelanda");
    countryMap.put("OM", "Omán");
    countryMap.put("NL", "Países Bajos");
    countryMap.put("PK", "Pakistán");
    countryMap.put("PW", "Palaos");
    countryMap.put("PS", "Palestina");
    countryMap.put("PA", "Panamá");
    countryMap.put("PG", "Papúa Nueva Guinea");
    countryMap.put("PY", "Paraguay");
    countryMap.put("PE", "Perú");
    countryMap.put("PF", "Polinesia Francesa");
    countryMap.put("PL", "Polonia");
    countryMap.put("PT", "Portugal");
    countryMap.put("PR", "Puerto Rico");
    countryMap.put("GB", "Reino Unido");
    countryMap.put("CF", "República Centroafricana");
    countryMap.put("CZ", "República Checa");
    countryMap.put("DO", "República Dominicana");
    countryMap.put("RE", "Reunión");
    countryMap.put("RW", "Ruanda");
    countryMap.put("RO", "Rumania");
    countryMap.put("RU", "Rusia");
    countryMap.put("EH", "Sahara Occidental");
    countryMap.put("WS", "Samoa");
    countryMap.put("AS", "Samoa Americana");
    countryMap.put("BL", "San Bartolomé");
    countryMap.put("KN", "San Cristóbal y Nieves");
    countryMap.put("SM", "San Marino");
    countryMap.put("MF", "San Martín (Francia)");
    countryMap.put("PM", "San Pedro y Miquelón");
    countryMap.put("VC", "San Vicente y las Granadinas");
    countryMap.put("SH", "Santa Elena");
    countryMap.put("LC", "Santa Lucía");
    countryMap.put("ST", "Santo Tomé y Príncipe");
    countryMap.put("SN", "Senegal");
    countryMap.put("RS", "Serbia");
    countryMap.put("SC", "Seychelles");
    countryMap.put("SL", "Sierra Leona");
    countryMap.put("SG", "Singapur");
    countryMap.put("SX", "Sint Maarten");
    countryMap.put("SY", "Siria");
    countryMap.put("SO", "Somalia");
    countryMap.put("LK", "Sri Lanka");
    countryMap.put("SZ", "Suazilandia");
    countryMap.put("ZA", "Sudáfrica");
    countryMap.put("SD", "Sudán");
    countryMap.put("SS", "Sudán del Sur");
    countryMap.put("SE", "Suecia");
    countryMap.put("CH", "Suiza");
    countryMap.put("SR", "Surinam");
    countryMap.put("SJ", "Svalbard y Jan Mayen");
    countryMap.put("TH", "Tailandia");
    countryMap.put("TW", "Taiwán");
    countryMap.put("TZ", "Tanzania");
    countryMap.put("TJ", "Tayikistán");
    countryMap.put("IO", "Territorio Británico del Océano Índico");
    countryMap.put("TF", "Territorios Australes Franceses");
    countryMap.put("TL", "Timor Oriental");
    countryMap.put("TG", "Togo");
    countryMap.put("TK", "Tokelau");
    countryMap.put("TO", "Tonga");
    countryMap.put("TT", "Trinidad y Tobago");
    countryMap.put("TN", "Túnez");
    countryMap.put("TM", "Turkmenistán");
    countryMap.put("TR", "Turquía");
    countryMap.put("TV", "Tuvalu");
    countryMap.put("UA", "Ucrania");
    countryMap.put("UG", "Uganda");
    countryMap.put("UY", "Uruguay");
    countryMap.put("UZ", "Uzbekistán");
    countryMap.put("VU", "Vanuatu");
    countryMap.put("VE", "Venezuela");
    countryMap.put("VN", "Vietnam");
    countryMap.put("WF", "Wallis y Futuna");
    countryMap.put("YE", "Yemen");
    countryMap.put("DJ", "Yibuti");
    countryMap.put("ZM", "Zambia");
    countryMap.put("ZW", "Zimbabue");

    return countryMap.getOrDefault(countryCode, countryCode);
  }
}
